version: '3'

services:
  # Django web application
  web:
    build: .
    container_name: django_web
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/book_worms

  # PostgreSQL database
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: book_worms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
